### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by ScalaWilliam** [ScalaConsultants/akka-persistence-eventsourcing#10]
OS: Windows 7 64-bit
Java 8 64-bit
Latest Activator

Create project, start it, then hit http://127.0.0.1:8080/api/vehicles
```
12:27:17.879 [seed-actor-system-akka.actor.default-dispatcher-2] INFO akka.event.slf4j.Slf4jLogger - Slf4jLogger started
12:27:17.892 [seed-actor-system-akka.actor.default-dispatcher-2] DEBUG akka.event.EventStream - logger log1-Slf4jLogger started
12:27:17.915 [seed-actor-system-akka.actor.default-dispatcher-2] DEBUG akka.event.EventStream - Default Loggers started
12:27:18.571 [seed-actor-system-akka.actor.default-dispatcher-3] DEBUG spray.can.server.HttpListener - Binding to /0.0.0.0:8080
12:27:18.622 [seed-actor-system-akka.actor.default-dispatcher-2] DEBUG akka.io.TcpListener - Successfully bound to /0:0:0:0:0:0:0:0:8080
12:27:18.626 [seed-actor-system-akka.actor.default-dispatcher-5] INFO spray.can.server.HttpListener - Bound to /0.0.0.0:8080
12:27:18.628 [seed-actor-system-akka.actor.default-dispatcher-3] INFO akka.actor.DeadLetterActorRef - Message [akka.io.Tcp$Bound] from Actor[akka://seed-actor-system/user/IO-HTTP/listener-0#-1182894253] to Actor[akka://seed-actor-system/deadLetters] was not delivered. [1] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
12:27:39.955 [seed-actor-system-akka.actor.default-dispatcher-3] DEBUG akka.io.TcpListener - New connection accepted
12:27:39.961 [seed-actor-system-akka.actor.default-dispatcher-3] DEBUG akka.io.TcpListener - New connection accepted
12:27:40.264 [seed-actor-system-akka.actor.default-dispatcher-3] DEBUG s.can.server.HttpServerConnection - Dispatching GET request to http://127.0.0.1:8080/api/vehicles to handler Actor[akka://seed-actor-system/system/IO-TCP/selectors/$a/1#-982467275]
12:27:40.304 [seed-actor-system-akka.actor.default-dispatcher-4] ERROR akka.actor.RepointableActorRef - Error during processing of request HttpRequest(GET,http://127.0.0.1:8080/api/vehicles,List(Cookie: PLAY_SESSION=dda106b2f3fb7c0ae696fad4f84df79498a778b8-csrfToken=65741f22d4391c00c78f3a47a33e68c0aa8489b5-1424127846019-5332226af2ab5d41f8235a67, Accept-Language: en-US, en, Accept-Encoding: gzip, deflate, sdch, User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.111 Safari/537.36, Connection: keep-alive, Host: 127.0.0.1:8080),Empty,HTTP/1.1)
java.lang.NullPointerException: null
at scala.concurrent.impl.Promise$DefaultPromise.onComplete(Promise.scala:268) ~[scala-library-2.11.2.jar:na]
at scala.concurrent.Future$class.map(Future.scala:235) ~[scala-library-2.11.2.jar:na]
at scala.concurrent.impl.Promise$DefaultPromise.map(Promise.scala:153) ~[scala-library-2.11.2.jar:na]
at spray.routing.authentication.HttpAuthenticator$class.apply(HttpAuthenticator.scala:36) ~[spray-routing_2.11-1.3.1.jar:na]
at spray.routing.authentication.BasicHttpAuthenticator.apply(HttpAuthenticator.scala:54) ~[spray-routing_2.11-1.3.1.jar:na]
at spray.routing.authentication.BasicHttpAuthenticator.apply(HttpAuthenticator.scala:54) ~[spray-routing_2.11-1.3.1.jar:na]
at spray.routing.directives.BasicDirectives$$anonfun$extract$1.apply(BasicDirectives.scala:86) ~[spray-routing_2.11-1.3.1.jar:na]
at spray.routing.directives.BasicDirectives$$anonfun$extract$1.apply(BasicDirectives.scala:86) ~[spray-routing_2.11-1.3.1.jar:na]
at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92) ~[spray-routing_2.11-1.3.1.jar:na]
at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92) ~[spray-routing_2.11-1.3.1.jar:na]
at spray.routing.directives.BasicDirectives$$anonfun$mapRequestContext$1$$anonfun$apply$1.apply(BasicDirectives.scala:30) ~[spray-routing_2.11-1.3.1.jar:na]
at spray.routing.directives.BasicDirectives$$anonfun$mapRequestContext$1$$anonfun$apply$1.apply(BasicDirectives.scala:30) ~[spray-routing_2.11-1.3.1.jar:na]
at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92) ~[spray-routing_2.11-1.3.1.jar:na]
at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92) ~[spray-routing_2.11-1.3.1.jar:na]
at spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1$$anonfun$apply$1.apply(RouteConcatenation.scala:32) ~[spray-routing_2.11-1.3.1.jar:na]
at spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1$$anonfun$apply$1.apply(RouteConcatenation.scala:31) ~[spray-routing_2.11-1.3.1.jar:na]
at spray.routing.RequestContext$$anonfun$withRejectionHandling$1.applyOrElse(RequestContext.scala:130) ~[spray-routing_2.11-1.3.1.jar:na]
at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) ~[scala-library-2.11.2.jar:0.13.5]
at spray.routing.RequestContext$$anon$1.handle(RequestContext.scala:84) ~[spray-routing_2.11-1.3.1.jar:na]
at akka.spray.UnregisteredActorRefBase.$bang(UnregisteredActorRefBase.scala:72) ~[spray-util_2.11-1.3.1.jar:na]
at spray.routing.RequestContext$$anon$3.handle(RequestContext.scala:102) ~[spray-routing_2.11-1.3.1.jar:na]
at akka.spray.UnregisteredActorRefBase.$bang(UnregisteredActorRefBase.scala:72) ~[spray-util_2.11-1.3.1.jar:na]
at spray.routing.RequestContext.reject(RequestContext.scala:202) ~[spray-routing_2.11-1.3.1.jar:na]
at spray.routing.directives.RouteDirectives$$anon$5.apply(RouteDirectives.scala:63) ~[spray-routing_2.11-1.3.1.jar:na]
at spray.routing.directives.RouteDirectives$$anon$5.apply(RouteDirectives.scala:62) ~[spray-routing_2.11-1.3.1.jar:na]
at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92) ~[spray-routing_2.11-1.3.1.jar:na]
at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92) ~[spray-routing_2.11-1.3.1.jar:na]
at spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1$$anonfun$apply$1.apply(RouteConcatenation.scala:32) ~[spray-routing_2.11-1.3.1.jar:na]
at spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1$$anonfun$apply$1.apply(RouteConcatenation.scala:31) ~[spray-routing_2.11-1.3.1.jar:na]
at spray.routing.RequestContext$$anonfun$withRejectionHandling$1.applyOrElse(RequestContext.scala:130) ~[spray-routing_2.11-1.3.1.jar:na]
at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) ~[scala-library-2.11.2.jar:0.13.5]
at spray.routing.RequestContext$$anon$1.handle(RequestContext.scala:84) ~[spray-routing_2.11-1.3.1.jar:na]
at akka.spray.UnregisteredActorRefBase.$bang(UnregisteredActorRefBase.scala:72) ~[spray-util_2.11-1.3.1.jar:na]
at spray.routing.RequestContext$$anon$3.handle(RequestContext.scala:102) ~[spray-routing_2.11-1.3.1.jar:na]
at akka.spray.UnregisteredActorRefBase.$bang(UnregisteredActorRefBase.scala:72) ~[spray-util_2.11-1.3.1.jar:na]
at spray.routing.RequestContext.reject(RequestContext.scala:202) ~[spray-routing_2.11-1.3.1.jar:na]
at spray.routing.directives.RouteDirectives$$anon$5.apply(RouteDirectives.scala:63) ~[spray-routing_2.11-1.3.1.jar:na]
at spray.routing.directives.RouteDirectives$$anon$5.apply(RouteDirectives.scala:62) ~[spray-routing_2.11-1.3.1.jar:na]
at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92) ~[spray-routing_2.11-1.3.1.jar:na]
at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92) ~[spray-routing_2.11-1.3.1.jar:na]
at spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1$$anonfun$apply$1.apply(RouteConcatenation.scala:32) ~[spray-routing_2.11-1.3.1.jar:na]
at spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1$$anonfun$apply$1.apply(RouteConcatenation.scala:31) ~[spray-routing_2.11-1.3.1.jar:na]
at spray.routing.RequestContext$$anonfun$withRejectionHandling$1.applyOrElse(RequestContext.scala:130) ~[spray-routing_2.11-1.3.1.jar:na]
at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) ~[scala-library-2.11.2.jar:0.13.5]
at spray.routing.RequestContext$$anon$1.handle(RequestContext.scala:84) ~[spray-routing_2.11-1.3.1.jar:na]
at akka.spray.UnregisteredActorRefBase.$bang(UnregisteredActorRefBase.scala:72) ~[spray-util_2.11-1.3.1.jar:na]
at spray.routing.RequestContext.reject(RequestContext.scala:202) ~[spray-routing_2.11-1.3.1.jar:na]
at spray.routing.directives.RouteDirectives$$anon$5.apply(RouteDirectives.scala:63) ~[spray-routing_2.11-1.3.1.jar:na]
at spray.routing.directives.RouteDirectives$$anon$5.apply(RouteDirectives.scala:62) ~[spray-routing_2.11-1.3.1.jar:na]
at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92) ~[spray-routing_2.11-1.3.1.jar:na]
at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92) ~[spray-routing_2.11-1.3.1.jar:na]
at spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1.apply(RouteConcatenation.scala:30) ~[spray-routing_2.11-1.3.1.jar:na]
at spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1.apply(RouteConcatenation.scala:29) ~[spray-routing_2.11-1.3.1.jar:na]
at spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1.apply(RouteConcatenation.scala:30) ~[spray-routing_2.11-1.3.1.jar:na]
at spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1.apply(RouteConcatenation.scala:29) ~[spray-routing_2.11-1.3.1.jar:na]
at spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1.apply(RouteConcatenation.scala:30) ~[spray-routing_2.11-1.3.1.jar:na]
at spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1.apply(RouteConcatenation.scala:29) ~[spray-routing_2.11-1.3.1.jar:na]
at spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1.apply(RouteConcatenation.scala:30) ~[spray-routing_2.11-1.3.1.jar:na]
at spray.routing.RouteConcatenation$RouteConcatenation$$anonfun$$tilde$1.apply(RouteConcatenation.scala:29) ~[spray-routing_2.11-1.3.1.jar:na]
at spray.routing.directives.BasicDirectives$$anonfun$mapRequestContext$1$$anonfun$apply$1.apply(BasicDirectives.scala:30) ~[spray-routing_2.11-1.3.1.jar:na]
at spray.routing.directives.BasicDirectives$$anonfun$mapRequestContext$1$$anonfun$apply$1.apply(BasicDirectives.scala:30) ~[spray-routing_2.11-1.3.1.jar:na]
at spray.routing.directives.BasicDirectives$$anonfun$mapRequestContext$1$$anonfun$apply$1.apply(BasicDirectives.scala:30) ~[spray-routing_2.11-1.3.1.jar:na]
at spray.routing.directives.BasicDirectives$$anonfun$mapRequestContext$1$$anonfun$apply$1.apply(BasicDirectives.scala:30) ~[spray-routing_2.11-1.3.1.jar:na]
at spray.routing.directives.BasicDirectives$$anonfun$mapRequestContext$1$$anonfun$apply$1.apply(BasicDirectives.scala:30) ~[spray-routing_2.11-1.3.1.jar:na]
at spray.routing.directives.BasicDirectives$$anonfun$mapRequestContext$1$$anonfun$apply$1.apply(BasicDirectives.scala:30) ~[spray-routing_2.11-1.3.1.jar:na]
at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92) ~[spray-routing_2.11-1.3.1.jar:na]
at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92) ~[spray-routing_2.11-1.3.1.jar:na]
at spray.routing.directives.BasicDirectives$$anonfun$mapRequestContext$1$$anonfun$apply$1.apply(BasicDirectives.scala:30) ~[spray-routing_2.11-1.3.1.jar:na]
at spray.routing.directives.BasicDirectives$$anonfun$mapRequestContext$1$$anonfun$apply$1.apply(BasicDirectives.scala:30) ~[spray-routing_2.11-1.3.1.jar:na]
at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92) ~[spray-routing_2.11-1.3.1.jar:na]
at spray.routing.directives.BasicDirectives$$anon$3$$anonfun$happly$1.apply(BasicDirectives.scala:92) ~[spray-routing_2.11-1.3.1.jar:na]
at spray.routing.directives.BasicDirectives$$anonfun$mapRequestContext$1$$anonfun$apply$1.apply(BasicDirectives.scala:30) ~[spray-routing_2.11-1.3.1.jar:na]
at spray.routing.directives.BasicDirectives$$anonfun$mapRequestContext$1$$anonfun$apply$1.apply(BasicDirectives.scala:30) ~[spray-routing_2.11-1.3.1.jar:na]
at spray.routing.directives.ExecutionDirectives$$anonfun$handleExceptions$1$$anonfun$apply$4.apply(ExecutionDirectives.scala:35) ~[spray-routing_2.11-1.3.1.jar:na]
at spray.routing.directives.ExecutionDirectives$$anonfun$handleExceptions$1$$anonfun$apply$4.apply(ExecutionDirectives.scala:33) ~[spray-routing_2.11-1.3.1.jar:na]
at spray.routing.HttpServiceBase$class.runSealedRoute$1(HttpService.scala:36) ~[spray-routing_2.11-1.3.1.jar:na]
at spray.routing.HttpServiceBase$$anonfun$runRoute$1.applyOrElse(HttpService.scala:46) ~[spray-routing_2.11-1.3.1.jar:na]
at akka.actor.Actor$class.aroundReceive(Actor.scala:465) ~[akka-actor_2.11-2.3.5.jar:na]
at io.scalac.seed.ServiceActor.aroundReceive(ServiceActor.scala:9) ~[classes/:na]
at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) [akka-actor_2.11-2.3.5.jar:na]
at akka.actor.ActorCell.invoke(ActorCell.scala:487) [akka-actor_2.11-2.3.5.jar:na]
at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:238) [akka-actor_2.11-2.3.5.jar:na]
at akka.dispatch.Mailbox.run(Mailbox.scala:220) [akka-actor_2.11-2.3.5.jar:na]
at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393) [akka-actor_2.11-2.3.5.jar:na]
at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.2.jar:na]
at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.2.jar:na]
at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.2.jar:na]
at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.2.jar:na]
```

**Comment by revati** [comment]
the same here with Java 8 on mac osx

**Comment by ceecer1** [comment]
Just played around with the example, same here java 8 on mac osx, any updates?

**Comment by yury-vashchyla** [comment]
I had some error. This happened because execution context is null. 
Just change line in ServiceActor from 
`override implicit val executionContext = context.dispatcher`  to 
` override implicit def executionContext = context.dispatcher`

**Comment by 4levels** [comment]
Hi, I ran into the same error, using HTTP Basic Auth with PostMan

The line 15 in file `src/main/scala/io/scalac/seed/ServiceActor.scala` to change currently looks like 
`implicit val executionContext = context.dispatcher`
and needs to be changed to 
`implicit def executionContext = context.dispatcher`
